-- MIA.DIVISAO_ADMINISTRATIVA definition

CREATE TABLE "MIA"."DIVISAO_ADMINISTRATIVA" 
   (	"NIVEL_1" NUMBER(2,0) DEFAULT NULL NOT NULL ENABLE, 
	"NIVEL_2" NUMBER(2,0) DEFAULT NULL NOT NULL ENABLE, 
	"NIVEL_3" NUMBER(3,0) DEFAULT NULL NOT NULL ENABLE, 
	"DESIGNACAO_DIVISAO_ADMIN" VARCHAR2(50) NOT NULL ENABLE, 
	"DATA_FIM" DATE, 
	"REGIAO" CHAR(1) NOT NULL ENABLE, 
	"DISTRITO_INE" VARCHAR2(2), 
	"CONCELHO_INE" VARCHAR2(2), 
	"FREGUESIA_INE" VARCHAR2(2), 
	 CONSTRAINT "CODIGO_DISTRITO7" CHECK (Nivel_1 BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "CODIGO_FREGUESIA7" CHECK (Nivel_3 BETWEEN 0 AND 999) ENABLE, 
	 CONSTRAINT "CODIGO_CONCELHO7" CHECK (Nivel_2 BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "ENUM_REGIAO2" CHECK (Regiao IN ('A', 'M', 'T')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIA_GRS_DATA_01" 
   CACHE ;
  CREATE INDEX "MIA"."TMP_HMS_SOCIAL_03_AC" ON "MIA"."DIVISAO_ADMINISTRATIVA" ("NIVEL_1", "NIVEL_2", "NIVEL_3", "DESIGNACAO_DIVISAO_ADMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIA_GRS_INDEX_01" ;
ALTER TABLE "MIA"."DIVISAO_ADMINISTRATIVA" ADD CONSTRAINT "DIVISAO_ADMINISTRATIVA_PK" PRIMARY KEY ("NIVEL_1", "NIVEL_2", "NIVEL_3")
  USING INDEX "MIA"."TMP_HMS_SOCIAL_03_AC"  ENABLE;

CREATE INDEX "MIA"."DA_DESIGNACAO_DIVISAO_ADMIN_AC" ON "MIA"."DIVISAO_ADMINISTRATIVA" ("DESIGNACAO_DIVISAO_ADMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5439488 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIA_GRS_INDEX_01" ;
  CREATE INDEX "MIA"."TMP_HMS_SOCIAL_03_AC" ON "MIA"."DIVISAO_ADMINISTRATIVA" ("NIVEL_1", "NIVEL_2", "NIVEL_3", "DESIGNACAO_DIVISAO_ADMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MIA_GRS_INDEX_01" ;

GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PF";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "USR_DEPLOY";
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "USR_DEPLOY";
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "HSIP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "HSIP";
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "HSIP";
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "HSIP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PF_V";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GESRISP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "OCIP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "RSI" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIG_SIP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIG_SIP";
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIG_SIP";
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIG_SIP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SAF" WITH GRANT OPTION;
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GIL";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SAF";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "CO";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "REE";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "COOP";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SEF_SEF";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "LNES_V" WITH GRANT OPTION;
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "LNES";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GREND";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ADOP";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "QGEN";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "IPSSCRS";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "DBA_DATINFOR";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SIPSC";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SGBS";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "SIPSC" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "AGULHAGEM";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ROLE_MIA_SELECT";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PS";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GRS";
  GRANT REFERENCES ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ID";
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ROLE_ALL_MIA_USR";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ROLE_ALL_MIA_USR";
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ROLE_ALL_MIA_USR";
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ROLE_ALL_MIA_USR";
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "QGEN" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PS" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PC" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GUS" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GTX" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GRS" WITH GRANT OPTION;
  GRANT UPDATE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ID" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "QGEN" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PC" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GUS" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GTX" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GRS" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ID" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "QGEN" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PS" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PC" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GUS" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GTX" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GRS" WITH GRANT OPTION;
  GRANT INSERT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ID" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "QGEN" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PS" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PC" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GUS" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GTX" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "GRS" WITH GRANT OPTION;
  GRANT DELETE ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "ID" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "PS" WITH GRANT OPTION;
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIE";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "MIE";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "DES_REE";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "DES_PF";
  GRANT SELECT ON "MIA"."DIVISAO_ADMINISTRATIVA" TO "DES_SIP";

COMMENT ON TABLE MIA.DIVISAO_ADMINISTRATIVA IS 'Divisões administrativas do território nacional, segundo a codificação atribuída pelo Instituto Nacional de Estatística.';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.NIVEL_1 IS '%AttDef';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.NIVEL_2 IS 'Nível 2 da divisão administrativa';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.NIVEL_3 IS 'Nível 3 da divisão administrativa';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.DESIGNACAO_DIVISAO_ADMIN IS 'Designação da divisão administrativa';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.DATA_FIM IS 'Data de fim de existência de divisão administrativa';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.REGIAO IS 'Indicação da região associada à divisão administrativa.';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.DISTRITO_INE IS 'Codificação de referência (INE) para distrito.';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.CONCELHO_INE IS 'Codificação de referência (INE) para concelho.';
COMMENT ON COLUMN MIA.DIVISAO_ADMINISTRATIVA.FREGUESIA_INE IS 'Codificação de referência (INE) para freguesia.';